### ISSUE TITLE
inline editing

### ISSUE THREAD

**Issue by filex** [malud/temgo#1]
`tg` is a nice replacement for `sed` when moving ENV vars to config files in docker entrypoint scripts!

however, the `tg < template > file` semantics forces me to use a separate template file. to keep things easy to read, i would prefer an _inline editing_ mode like `sed -i`:

```
tg -i my.conf
```

the command should be idempotent to avoid changes to the file when the docker container is restarted. ideally, subsequent runs would not write the file at all (because no placeholder was found).

**Comment by malud** [comment]
I have added this option.

`tg` will change the given file if placeholders are found. Above all on docker container restarts but would produce always the same output. Based on template files baked into the container.

Write Condition: https://github.com/malud/temgo/blob/master/cli/cli.go#L43

New Release: https://github.com/malud/temgo/releases/tag/0.1.4
