### ISSUE TITLE
no output without placeholders

### ISSUE THREAD

**Issue by filex** [malud/temgo#2]
When the input stream has no placeholders, `tg` generates no output:

Expected:
```
$ echo foo bar | ./tg
foo bar
```

Actual:
```
$ echo foo bar | ./tg
```

With _correct_ placeholders, it works as expected:
```
$ echo 'foo {{ x }}bar' | ./tg
foo bar
```

However, _incomplete_ placeholders show the erroneous behaviour, too:
```
$ echo 'foo {{ }}bar' | ./tg
$ echo 'foo {{x}}bar' | ./tg
$ echo 'foo {{x }}bar' | ./tg
```

**Comment by malud** [comment]
Thanks for your bug submission. I have fixed this issue.

`temgo` shouldn't replace variables with an empty string if they are not set. This behaviour is fixed too.
