### ISSUE TITLE
Feature Request: strict mode – fail on missing vars

### ISSUE THREAD

**Issue by filex** [malud/temgo#4]
I want to propose a _strict mode_ that makes `tg` fail if a placeholder cannot be replaced.

```
$ echo '{{ NOT_SET }}' | tg -s
Error: placeholder NOT_SET cannot be replaced
$ echo $?
1
```

My use case is as usual a docker container's entrypoint. I use `tg` to fill env vars into configuration files. The configuration file may be broken if a placeholder is not replaced. In the entrypoint I have to check that every env variable used in placeholders is set. This is error prone, because I have at least two places to get it wrong.

With `tg -s` I would be able to let my `set -e` entrypoint fail without repeating the variable list.

The stdout variant `tg -s > file` will empty the file because bash opens the redirection before the command is executed.

But in inplace mode `tg -s -i file` the output file should not be written at all, if a variable is missing.

**Comment by filex** [comment]
Replacements with default values (#3) should be considered "set" and should never trigger an error in strict mode. The error condition is not "variable missing" but rather "replacement failed".

**Comment by malud** [comment]
Thanks for your proposal. I have implemented this feature and created a release. https://github.com/malud/temgo/releases/tag/0.2
