### ISSUE TITLE
Feature request: Make temgo fail if a variable is not set

### ISSUE THREAD

**Issue by bemeyert** [malud/temgo#6]
This feature would be quite useful for saving a lot of code (depends on the number of variables). Currently I do something like this:
```sh
set -o errexit
set -o unset

[[ -z ${HTTP_SERVER} ]] && :
[[ -z ${HTTPS_SERVER} ]] && :
[[ -z ${DB_HOSTNAME} ]] && :
[[ -z ${DB_USERNAME} ]] && :
[[ -z ${DB_PASSWORD} ]] && :
[[ -z ${DB_DATABASE} ]] && :
[[ -z ${DB_PORT} ]] && :
[[ -z ${DB_PREFIX} ]] && :
[[ -z ${ADMIN_HTTP_SERVER} ]] && :
[[ -z ${ADMIN_HTTP_CATALOG} ]] && :
[[ -z ${ADMIN_HTTPS_SERVER} ]] && :
[[ -z ${ADMIN_HTTPS_CATALOG} ]] && :

tg -i /app/config.php
```
If `temgo` failed when a variable is not set, let's say with the `-f` switch (force/fail), the above would look like this:
```sh
set -o errexit
tg -f -i /app/config.php
```
The savings on nerves and typing would be enormous ;)

Cheers

**Comment by malud** [comment]
Shame on me. There is a undocumented option called `strict` mode.

`tg -s -i /app/config.php` would do the trick already. I will leave this issue open for a documentation update.
